message("myemptyConfigVersion.cmake called by find_package(${CMAKE_FIND_PACKAGE_NAME})")

printVars(
        CMAKE_FIND_PACKAGE_NAME
        ${CMAKE_FIND_PACKAGE_NAME}_FIND_REQUIRED
        ${CMAKE_FIND_PACKAGE_NAME}_FIND_QUIETLY
        ${CMAKE_FIND_PACKAGE_NAME}_FIND_VERSION
        ${CMAKE_FIND_PACKAGE_NAME}_FIND_VERSION_MAJOR
        ${CMAKE_FIND_PACKAGE_NAME}_FIND_VERSION_MINOR
        ${CMAKE_FIND_PACKAGE_NAME}_FIND_VERSION_PATCH
        ${CMAKE_FIND_PACKAGE_NAME}_FIND_VERSION_EXACT

)

set(PACKAGE_VERSION_COMPATIBLE TRUE)
set(PACKAGE_VERSION_EXACT TRUE)